### ISSUE TITLE
25/08 - todo list & thoughts

### ISSUE THREAD

**Issue by Antholimere** [AnaYs/mcl#3]
I think it may be nice to look at each-others opinion on how to progress on MCL by making a raw to-do list so we can make a track-plan afterwards.

The biggest functionality of the website will be the way 'code-snippets' are visualised. So my idea is to make a static version of it and make it dynamic afterwards. This way we can see what we want before the need of actually making the link with the back-end side of it. 

Where I'm getting it is that I think the core MCL functionality can be made front-end first, then we can analyse what the possibilities. Off course I'll be pushing the website's basic front-end layout first!

Maybe integrating devise, FB-login and pundit can be the back-end for now? What do you think

**Comment by Antholimere** [comment]
Questions:
-Collect testimonies before releasing? (yes it's possible)
-Rename code-snippets to cheatsheets? Does this include visuals?
-Keep visuals for v2 (if animated)? else work with statics
-What languages to introduce with I18n?
-Work with usernames instead of e-mail adresses?
-What kind of social features should be integrated (Chat, PM, ..)? Chat may be too hard though, let's keep it for v4 when we can hire a pro.
-How will MCL represent code-snippets/cheatsheets for each user. Snippets inside libraries - separate snippets and unite them by tags?  
-Make the user have private/personal snippets and public ones aka share-able? 
-What kind of rating system will there be when sharing snippets? 
-Commenting on snippets?
-Giving the possibility to users to make collaborative snippets? - improving snippets through community effort (only works in case of 'big snippets' aka libraries?) 'open-source snippets'

**Comment by AnaYs** [comment]
Antho, I made a trello last week for mcl but I didnt share it with you because I just used it to structure my thoughts. I added now what you wrote here so maybe we can move this to discussion to trello? issues should remain for technical issues coding-wise. In trello there is 
- ToDo lists on basic architecture, front-end, private/public code snippets and social features
- To Discuss card with issues that I think we should narrow down to be on the same page for V1

Added your email (anthonylimere@gmail.com) to the trello board: https://trello.com/b/WODcUnyS/mcl
